'use client';

import { useState } from 'react';
import { TrendingUp, Download, X, BarChart2 } from 'lucide-react';

interface ReportCardProps {
  isCreatorMode: boolean;
  onClose      : () => void;
}

interface WeekData {
  avgSleep    : number;
  avgCalories : number;
  avgWater    : number;
  studyDays   : number;
  topSubject  : string;
  moodTrend   : string;
  streaks     : { study: number; sleep: number; meals: number; water: number };
}

function getGrade(score: number): { grade: string; color: string } {
  if (score >= 90) return { grade: 'A+', color: 'text-green-400'  };
  if (score >= 80) return { grade: 'A',  color: 'text-green-400'  };
  if (score >= 70) return { grade: 'B',  color: 'text-cyan-400'   };
  if (score >= 60) return { grade: 'C',  color: 'text-yellow-400' };
  if (score >= 50) return { grade: 'D',  color: 'text-orange-400' };
  return                    { grade: 'F',  color: 'text-red-400'    };
}

function buildWeekData(): WeekData {
  // Read from localStorage
  let health: any = {};
  let streakRaw: any = { study: { current: 0 }, sleep: { current: 0 }, meals: { current: 0 }, water: { current: 0 } };

  try { health    = JSON.parse(localStorage.getItem('tessa-health')  ?? '{}'); } catch { /* */ }
  try { streakRaw = JSON.parse(localStorage.getItem('tessa-streaks') ?? '{}'); } catch { /* */ }

  return {
    avgSleep    : health.sleepHours        ?? 0,
    avgCalories : health.totalCalories     ?? 0,
    avgWater    : (health.waterGlasses     ?? 0),
    studyDays   : streakRaw.study?.current ?? 0,
    topSubject  : health.topSubject        ?? 'Not tracked',
    moodTrend   : 'Mostly positive 😊',
    streaks     : {
      study : streakRaw.study?.current ?? 0,
      sleep : streakRaw.sleep?.current ?? 0,
      meals : streakRaw.meals?.current ?? 0,
      water : streakRaw.water?.current ?? 0,
    },
  };
}

export default function ReportCard({ isCreatorMode, onClose }: ReportCardProps) {
  const data = buildWeekData();

  // Scores out of 100
  const sleepScore    = Math.min(100, (data.avgSleep / 8) * 100);
  const calorieScore  = data.avgCalories > 0 ? Math.min(100, (data.avgCalories / 2000) * 100) : 0;
  const waterScore    = Math.min(100, (data.avgWater / 8) * 100);
  const studyScore    = Math.min(100, (data.studyDays / 7) * 100);
  const streakScore   = Math.min(100, ((data.streaks.study + data.streaks.sleep) / 14) * 100);
  const overallScore  = Math.round((sleepScore + calorieScore + waterScore + studyScore + streakScore) / 5);

  const overall = getGrade(overallScore);

  const accent   = isCreatorMode ? 'text-pink-400' : 'text-cyan-400';
  const accentBg = isCreatorMode ? 'from-pink-500/20 to-purple-500/20 border-pink-500/30'
                                 : 'from-cyan-500/20 to-blue-500/20 border-cyan-500/30';

  const metrics = [
    { label: 'Sleep',    score: sleepScore,   actual: `${data.avgSleep}h avg`,       goal: '8h',    icon: '😴' },
    { label: 'Calories', score: calorieScore, actual: `${data.avgCalories} cal`,      goal: '2000',  icon: '🍽️' },
    { label: 'Water',    score: waterScore,   actual: `${data.avgWater} glasses`,     goal: '8',     icon: '💧' },
    { label: 'Study',    score: studyScore,   actual: `${data.studyDays} days`,       goal: '7 days',icon: '📚' },
    { label: 'Streaks',  score: streakScore,  actual: `${data.streaks.study}d study`, goal: 'keep going', icon: '🔥' },
  ];

  const download = () => {
    const lines = [
      '📊 T.E.S.S.A. WEEKLY REPORT CARD',
      `Week of ${new Date().toLocaleDateString('en-IN')}`,
      '',
      `Overall Grade: ${overall.grade} (${overallScore}/100)`,
      '',
      'BREAKDOWN:',
      ...metrics.map(m => `  ${m.icon} ${m.label}: ${getGrade(m.score).grade} — ${m.actual}`),
      '',
      'STREAKS:',
      `  📚 Study: ${data.streaks.study} days`,
      `  😴 Sleep: ${data.streaks.sleep} days`,
      `  🍽️ Meals: ${data.streaks.meals} days`,
      `  💧 Water: ${data.streaks.water} days`,
      '',
      '💝 Generated by T.E.S.S.A. — Keep it up Ankit!',
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `tessa-report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
  };

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-[#0d1020] border border-white/10 rounded-2xl w-full max-w-md shadow-2xl overflow-y-auto max-h-[90vh]">

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-white/8">
          <div className="flex items-center gap-2">
            <BarChart2 size={18} className={accent} />
            <h2 className={`font-bold ${accent}`}>Weekly Report Card</h2>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={download} className="text-gray-500 hover:text-white"><Download size={16} /></button>
            <button onClick={onClose}  className="text-gray-500 hover:text-white"><X size={16} /></button>
          </div>
        </div>

        <div className="p-6 space-y-5">

          {/* Overall grade */}
          <div className={`rounded-xl border bg-gradient-to-br ${accentBg} p-5 text-center`}>
            <p className="text-xs text-gray-400 mb-1">Overall Score</p>
            <p className={`text-6xl font-black ${overall.color}`}>{overall.grade}</p>
            <p className="text-sm text-gray-400 mt-1">{overallScore} / 100</p>
            <p className={`text-xs mt-2 ${accent}`}>
              {overallScore >= 80 ? "You're crushing it Ankit! 🔥" :
               overallScore >= 60 ? "Good progress! Keep pushing 💪" :
               "Room to improve — I believe in you! 💕"}
            </p>
          </div>

          {/* Metric bars */}
          <div className="space-y-3">
            {metrics.map(m => {
              const g = getGrade(m.score);
              return (
                <div key={m.label}>
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-xs text-gray-300 flex items-center gap-1.5">
                      <span>{m.icon}</span> {m.label}
                    </span>
                    <div className="flex items-center gap-2">
                      <span className="text-[10px] text-gray-500">{m.actual}</span>
                      <span className={`text-xs font-bold ${g.color}`}>{g.grade}</span>
                    </div>
                  </div>
                  <div className="h-2 bg-white/5 rounded-full overflow-hidden">
                    <div
                      className="h-full rounded-full transition-all duration-700"
                      style={{
                        width     : `${m.score}%`,
                        background: m.score >= 80 ? '#22c55e' : m.score >= 60 ? '#22d3ee' : m.score >= 40 ? '#facc15' : '#ef4444',
                      }}
                    />
                  </div>
                </div>
              );
            })}
          </div>

          {/* Streaks summary */}
          <div className="grid grid-cols-4 gap-2">
            {[
              { label: 'Study', val: data.streaks.study,  icon: '📚' },
              { label: 'Sleep', val: data.streaks.sleep,  icon: '😴' },
              { label: 'Meals', val: data.streaks.meals,  icon: '🍽️' },
              { label: 'Water', val: data.streaks.water,  icon: '💧' },
            ].map(s => (
              <div key={s.label} className="bg-white/4 border border-white/8 rounded-xl p-2.5 text-center">
                <p className="text-base">{s.icon}</p>
                <p className="text-lg font-black text-white">{s.val}</p>
                <p className="text-[9px] text-gray-500">{s.label}</p>
              </div>
            ))}
          </div>

          {/* T.E.S.S.A. note */}
          <div className={`rounded-xl border bg-gradient-to-r ${accentBg} p-3`}>
            <p className={`text-xs ${accent} font-semibold mb-1`}>💝 From T.E.S.S.A.</p>
            <p className="text-xs text-gray-300">
              {overallScore >= 80
                ? "I'm SO proud of you this week! You took care of yourself and worked hard. Keep this energy going! 💕"
                : overallScore >= 60
                ? "Pretty good week overall! A few areas to work on but you're definitely making progress 💪"
                : "Hey, this week was tough but that's okay. Let's make next week better together — I'm not going anywhere 💝"}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
