// FOOD DATABASE — Indian & International, calories per standard serving
// All values are per-piece/per-cup/per-standard-serving unless noted

interface FoodItem {
  food      : string;
  calories  : number;
  confidence: string;
  unit      : string;   // what "1 serving" means
}

const FOOD_DATABASE: Record<string, { cal: number; unit: string }> = {
  // ═══ RICE & GRAINS (per cup cooked) ═══
  'plain rice':        { cal: 206, unit: 'per cup' },
  'white rice':        { cal: 206, unit: 'per cup' },
  'basmati rice':      { cal: 190, unit: 'per cup' },
  'brown rice':        { cal: 216, unit: 'per cup' },
  'jeera rice':        { cal: 250, unit: 'per cup' },
  'ghee rice':         { cal: 300, unit: 'per cup' },
  'biryani':           { cal: 450, unit: 'per plate' },
  'chicken biryani':   { cal: 490, unit: 'per plate' },
  'mutton biryani':    { cal: 540, unit: 'per plate' },
  'veg biryani':       { cal: 380, unit: 'per plate' },
  'egg biryani':       { cal: 430, unit: 'per plate' },
  'hyderabadi biryani':{ cal: 510, unit: 'per plate' },
  'fried rice':        { cal: 350, unit: 'per cup' },
  'veg fried rice':    { cal: 320, unit: 'per cup' },
  'chicken fried rice':{ cal: 380, unit: 'per cup' },
  'egg fried rice':    { cal: 360, unit: 'per cup' },
  'pulao':             { cal: 280, unit: 'per cup' },
  'khichdi':           { cal: 200, unit: 'per cup' },
  'pongal':            { cal: 240, unit: 'per cup' },

  // ═══ ROTI & BREADS (per piece) ═══
  'roti':              { cal: 70,  unit: 'per piece' },
  'chapati':           { cal: 70,  unit: 'per piece' },
  'phulka':            { cal: 65,  unit: 'per piece' },
  'tandoori roti':     { cal: 120, unit: 'per piece' },
  'butter roti':       { cal: 130, unit: 'per piece' },
  'paratha':           { cal: 200, unit: 'per piece' },
  'aloo paratha':      { cal: 260, unit: 'per piece' },
  'gobi paratha':      { cal: 230, unit: 'per piece' },
  'paneer paratha':    { cal: 280, unit: 'per piece' },
  'methi paratha':     { cal: 210, unit: 'per piece' },
  'lachha paratha':    { cal: 290, unit: 'per piece' },
  'naan':              { cal: 260, unit: 'per piece' },
  'butter naan':       { cal: 320, unit: 'per piece' },
  'garlic naan':       { cal: 295, unit: 'per piece' },
  'cheese naan':       { cal: 360, unit: 'per piece' },
  'puri':              { cal: 90,  unit: 'per piece' },
  'bhatura':           { cal: 210, unit: 'per piece' },
  'chole bhature':     { cal: 480, unit: 'per plate' },
  'kachori':           { cal: 190, unit: 'per piece' },
  'bread slice':       { cal: 80,  unit: 'per slice' },
  'bread':             { cal: 80,  unit: 'per slice' },
  'brown bread':       { cal: 70,  unit: 'per slice' },
  'toast':             { cal: 70,  unit: 'per slice' },
  'butter toast':      { cal: 130, unit: 'per slice' },
  'sandwich':          { cal: 280, unit: 'per sandwich' },
  'veg sandwich':      { cal: 250, unit: 'per sandwich' },
  'cheese sandwich':   { cal: 310, unit: 'per sandwich' },
  'grilled sandwich':  { cal: 320, unit: 'per sandwich' },

  // ═══ DAL & LENTILS (per bowl ~200ml) ═══
  'dal':               { cal: 140, unit: 'per bowl' },
  'dal tadka':         { cal: 160, unit: 'per bowl' },
  'dal fry':           { cal: 170, unit: 'per bowl' },
  'dal makhani':       { cal: 220, unit: 'per bowl' },
  'rajma':             { cal: 200, unit: 'per bowl' },
  'rajma masala':      { cal: 220, unit: 'per bowl' },
  'chole':             { cal: 200, unit: 'per bowl' },
  'chole masala':      { cal: 230, unit: 'per bowl' },
  'sambar':            { cal: 100, unit: 'per bowl' },
  'rasam':             { cal: 50,  unit: 'per bowl' },

  // ═══ PANEER (per bowl/serving) ═══
  'paneer':            { cal: 265, unit: 'per 100g' },
  'paneer butter masala': { cal: 340, unit: 'per bowl' },
  'paneer tikka masala':  { cal: 320, unit: 'per bowl' },
  'palak paneer':      { cal: 240, unit: 'per bowl' },
  'matar paneer':      { cal: 260, unit: 'per bowl' },
  'kadai paneer':      { cal: 290, unit: 'per bowl' },
  'paneer bhurji':     { cal: 250, unit: 'per bowl' },
  'shahi paneer':      { cal: 370, unit: 'per bowl' },
  'paneer tikka':      { cal: 280, unit: 'per plate' },

  // ═══ VEGETABLE CURRIES (per bowl) ═══
  'aloo curry':        { cal: 180, unit: 'per bowl' },
  'aloo gobi':         { cal: 150, unit: 'per bowl' },
  'aloo matar':        { cal: 160, unit: 'per bowl' },
  'baingan bharta':    { cal: 200, unit: 'per bowl' },
  'bhindi masala':     { cal: 130, unit: 'per bowl' },
  'mix veg curry':     { cal: 150, unit: 'per bowl' },
  'mushroom curry':    { cal: 140, unit: 'per bowl' },

  // ═══ CHICKEN & MEAT (per serving/piece) ═══
  'chicken curry':     { cal: 300, unit: 'per bowl' },
  'butter chicken':    { cal: 380, unit: 'per bowl' },
  'chicken tikka masala': { cal: 370, unit: 'per bowl' },
  'chicken tikka':     { cal: 250, unit: 'per plate' },
  'tandoori chicken':  { cal: 200, unit: 'per piece' },
  'chicken leg':       { cal: 220, unit: 'per piece' },
  'chicken breast':    { cal: 165, unit: 'per 100g' },
  'chicken wings':     { cal: 100, unit: 'per piece' },
  'chicken nuggets':   { cal: 60,  unit: 'per piece' },
  'chicken lollipop':  { cal: 80,  unit: 'per piece' },
  'grilled chicken':   { cal: 165, unit: 'per 100g' },
  'mutton curry':      { cal: 350, unit: 'per bowl' },
  'mutton korma':      { cal: 390, unit: 'per bowl' },
  'fish curry':        { cal: 200, unit: 'per bowl' },
  'fish fry':          { cal: 230, unit: 'per piece' },
  'egg curry':         { cal: 170, unit: 'per bowl' },
  'boiled egg':        { cal: 70,  unit: 'per egg' },
  'fried egg':         { cal: 90,  unit: 'per egg' },
  'omelette':          { cal: 150, unit: 'per egg' },
  'egg':               { cal: 70,  unit: 'per egg' },
  'scrambled eggs':    { cal: 170, unit: 'per serving' },

  // ═══ SOUTH INDIAN (per piece) ═══
  'dosa':              { cal: 130, unit: 'per piece' },
  'masala dosa':       { cal: 200, unit: 'per piece' },
  'plain dosa':        { cal: 130, unit: 'per piece' },
  'rava dosa':         { cal: 160, unit: 'per piece' },
  'mysore masala dosa':{ cal: 230, unit: 'per piece' },
  'idli':              { cal: 40,  unit: 'per piece' },
  'rava idli':         { cal: 65,  unit: 'per piece' },
  'medu vada':         { cal: 90,  unit: 'per piece' },
  'vada':              { cal: 90,  unit: 'per piece' },
  'uttapam':           { cal: 170, unit: 'per piece' },
  'upma':              { cal: 170, unit: 'per bowl' },
  'poha':              { cal: 200, unit: 'per bowl' },
  'appam':             { cal: 100, unit: 'per piece' },
  'puttu':             { cal: 140, unit: 'per serving' },

  // ═══ SNACKS & STREET FOOD (per piece) ═══
  'samosa':            { cal: 262, unit: 'per piece' },
  'aloo samosa':       { cal: 262, unit: 'per piece' },
  'paneer samosa':     { cal: 290, unit: 'per piece' },
  'pakora':            { cal: 50,  unit: 'per piece' },
  'onion pakora':      { cal: 45,  unit: 'per piece' },
  'aloo pakora':       { cal: 60,  unit: 'per piece' },
  'bread pakora':      { cal: 150, unit: 'per piece' },
  'tikki':             { cal: 110, unit: 'per piece' },
  'aloo tikki':        { cal: 120, unit: 'per piece' },
  'cutlet':            { cal: 140, unit: 'per piece' },
  'kebab':             { cal: 100, unit: 'per piece' },
  'seekh kebab':       { cal: 110, unit: 'per piece' },
  'hara bhara kebab':  { cal: 90,  unit: 'per piece' },
  'pani puri':         { cal: 35,  unit: 'per piece' },
  'golgappa':          { cal: 35,  unit: 'per piece' },
  'pav bhaji':         { cal: 370, unit: 'per plate' },
  'vada pav':          { cal: 250, unit: 'per piece' },
  'momos':             { cal: 35,  unit: 'per piece' },
  'veg momos':         { cal: 30,  unit: 'per piece' },
  'chicken momos':     { cal: 40,  unit: 'per piece' },
  'fried momos':       { cal: 55,  unit: 'per piece' },
  'spring roll':       { cal: 80,  unit: 'per piece' },
  'chaat':             { cal: 200, unit: 'per plate' },
  'aloo chaat':        { cal: 200, unit: 'per plate' },
  'bhel puri':         { cal: 150, unit: 'per plate' },
  'dahi puri':         { cal: 140, unit: 'per plate' },

  // ═══ FAST FOOD ═══
  'pizza':             { cal: 285, unit: 'per slice' },
  'margherita pizza':  { cal: 250, unit: 'per slice' },
  'veg pizza':         { cal: 270, unit: 'per slice' },
  'chicken pizza':     { cal: 310, unit: 'per slice' },
  'burger':            { cal: 300, unit: 'per burger' },
  'veg burger':        { cal: 270, unit: 'per burger' },
  'chicken burger':    { cal: 320, unit: 'per burger' },
  'cheese burger':     { cal: 340, unit: 'per burger' },
  'pasta':             { cal: 310, unit: 'per bowl' },
  'maggi':             { cal: 205, unit: 'per packet' },
  'instant noodles':   { cal: 190, unit: 'per packet' },
  'noodles':           { cal: 295, unit: 'per bowl' },
  'chowmein':          { cal: 295, unit: 'per bowl' },
  'hakka noodles':     { cal: 300, unit: 'per bowl' },
  'french fries':      { cal: 312, unit: 'per medium serving' },
  'manchurian':        { cal: 220, unit: 'per bowl' },
  'gobi manchurian':   { cal: 220, unit: 'per bowl' },
  'chili chicken':     { cal: 290, unit: 'per bowl' },

  // ═══ SOUPS (per bowl) ═══
  'vegetable soup':    { cal: 55,  unit: 'per bowl' },
  'tomato soup':       { cal: 75,  unit: 'per bowl' },
  'sweet corn soup':   { cal: 85,  unit: 'per bowl' },
  'manchow soup':      { cal: 100, unit: 'per bowl' },
  'chicken soup':      { cal: 95,  unit: 'per bowl' },
  'clear soup':        { cal: 40,  unit: 'per bowl' },

  // ═══ DESSERTS & SWEETS (per piece/serving) ═══
  'gulab jamun':       { cal: 150, unit: 'per piece' },
  'rasgulla':          { cal: 106, unit: 'per piece' },
  'rasmalai':          { cal: 115, unit: 'per piece' },
  'jalebi':            { cal: 150, unit: 'per piece' },
  'ladoo':             { cal: 120, unit: 'per piece' },
  'besan ladoo':       { cal: 130, unit: 'per piece' },
  'barfi':             { cal: 130, unit: 'per piece' },
  'kaju barfi':        { cal: 150, unit: 'per piece' },
  'halwa':             { cal: 200, unit: 'per bowl' },
  'gajar halwa':       { cal: 250, unit: 'per bowl' },
  'kheer':             { cal: 180, unit: 'per bowl' },
  'kulfi':             { cal: 155, unit: 'per stick' },
  'ice cream':         { cal: 200, unit: 'per scoop' },
  'chocolate':         { cal: 150, unit: 'per bar (30g)' },
  'cake':              { cal: 270, unit: 'per slice' },
  'pastry':            { cal: 290, unit: 'per piece' },
  'muffin':            { cal: 380, unit: 'per piece' },
  'cookie':            { cal: 80,  unit: 'per piece' },
  'biscuit':           { cal: 50,  unit: 'per piece' },
  'kaju katli':        { cal: 60,  unit: 'per piece' },

  // ═══ BEVERAGES ═══
  'tea':               { cal: 30,  unit: 'per cup' },
  'chai':              { cal: 45,  unit: 'per cup' },
  'masala chai':       { cal: 55,  unit: 'per cup' },
  'green tea':         { cal: 2,   unit: 'per cup' },
  'black coffee':      { cal: 2,   unit: 'per cup' },
  'milk coffee':       { cal: 65,  unit: 'per cup' },
  'cappuccino':        { cal: 120, unit: 'per cup' },
  'latte':             { cal: 150, unit: 'per cup' },
  'cold coffee':       { cal: 180, unit: 'per glass' },
  'coffee':            { cal: 5,   unit: 'per cup' },
  'milkshake':         { cal: 260, unit: 'per glass' },
  'lassi':             { cal: 160, unit: 'per glass' },
  'sweet lassi':       { cal: 180, unit: 'per glass' },
  'mango lassi':       { cal: 190, unit: 'per glass' },
  'buttermilk':        { cal: 40,  unit: 'per glass' },
  'chaas':             { cal: 40,  unit: 'per glass' },
  'nimbu pani':        { cal: 60,  unit: 'per glass' },
  'coconut water':     { cal: 45,  unit: 'per glass' },
  'fruit juice':       { cal: 110, unit: 'per glass' },
  'orange juice':      { cal: 110, unit: 'per glass' },
  'apple juice':       { cal: 115, unit: 'per glass' },
  'milk':              { cal: 120, unit: 'per glass (200ml)' },
  'smoothie':          { cal: 200, unit: 'per glass' },
  'protein shake':     { cal: 130, unit: 'per scoop serving' },

  // ═══ FRUITS (per piece/100g) ═══
  'apple':             { cal: 80,  unit: 'per medium' },
  'banana':            { cal: 100, unit: 'per medium' },
  'mango':             { cal: 100, unit: 'per medium' },
  'orange':            { cal: 60,  unit: 'per medium' },
  'grapes':            { cal: 100, unit: 'per cup' },
  'watermelon':        { cal: 85,  unit: 'per slice' },
  'papaya':            { cal: 65,  unit: 'per cup' },
  'guava':             { cal: 68,  unit: 'per piece' },
  'kiwi':              { cal: 42,  unit: 'per piece' },
  'strawberry':        { cal: 32,  unit: 'per 100g' },
  'dates':             { cal: 70,  unit: 'per piece' },

  // ═══ NUTS & DRY FRUITS (per handful ~30g) ═══
  'almonds':           { cal: 170, unit: 'per handful (30g)' },
  'badam':             { cal: 170, unit: 'per handful (30g)' },
  'cashew':            { cal: 165, unit: 'per handful (30g)' },
  'kaju':              { cal: 165, unit: 'per handful (30g)' },
  'peanuts':           { cal: 170, unit: 'per handful (30g)' },
  'walnuts':           { cal: 190, unit: 'per handful (30g)' },
  'dry fruits':        { cal: 150, unit: 'per handful (30g)' },

  // ═══ DAIRY (per serving) ═══
  'curd':              { cal: 60,  unit: 'per 100g' },
  'dahi':              { cal: 60,  unit: 'per 100g' },
  'yogurt':            { cal: 60,  unit: 'per 100g' },
  'greek yogurt':      { cal: 100, unit: 'per 100g' },
  'paneer raw':        { cal: 265, unit: 'per 100g' },
  'butter':            { cal: 100, unit: 'per tbsp' },
  'ghee':              { cal: 120, unit: 'per tbsp' },
  'cheese slice':      { cal: 80,  unit: 'per slice' },
  'cheese':            { cal: 110, unit: 'per slice' },

  // ═══ SALADS (per plate) ═══
  'green salad':       { cal: 35,  unit: 'per plate' },
  'mixed salad':       { cal: 60,  unit: 'per plate' },
  'fruit salad':       { cal: 90,  unit: 'per bowl' },
  'kachumber':         { cal: 40,  unit: 'per bowl' },
  'caesar salad':      { cal: 190, unit: 'per plate' },

  // ═══ BREAKFAST ═══
  'oats':              { cal: 150, unit: 'per bowl cooked' },
  'porridge':          { cal: 150, unit: 'per bowl' },
  'daliya':            { cal: 150, unit: 'per bowl' },
  'cornflakes':        { cal: 200, unit: 'per bowl with milk' },
  'muesli':            { cal: 250, unit: 'per bowl with milk' },

  // ═══ CONDIMENTS ═══
  'raita':             { cal: 70,  unit: 'per bowl' },
  'chutney':           { cal: 30,  unit: 'per tbsp' },
  'papad':             { cal: 50,  unit: 'per piece' },
  'chips':             { cal: 150, unit: 'per small pack' },
  'namkeen':           { cal: 140, unit: 'per small pack' },

  // ═══ SOYA & MOCK MEAT (per bowl/serving) ═══
  'soya chaap':              { cal: 280, unit: 'per plate' },
  'soya chaap curry':        { cal: 310, unit: 'per bowl' },
  'malai soya chaap':        { cal: 380, unit: 'per plate' },
  'tandoori soya chaap':     { cal: 260, unit: 'per plate' },
  'afghani soya chaap':      { cal: 350, unit: 'per plate' },
  'achari soya chaap':       { cal: 300, unit: 'per plate' },
  'soya chaap gravy':        { cal: 310, unit: 'per bowl' },
  'soya chaap masala':       { cal: 300, unit: 'per bowl' },
  'soya chaap tikka':        { cal: 250, unit: 'per plate' },
  'soya chaap roll':         { cal: 320, unit: 'per roll' },
  'soyabean curry':          { cal: 220, unit: 'per bowl' },
  'soya curry':              { cal: 220, unit: 'per bowl' },
  'soya chunks curry':       { cal: 230, unit: 'per bowl' },
  'soya chunks':             { cal: 345, unit: 'per 100g dry' },
  'soya tikka':              { cal: 200, unit: 'per plate' },
  'soya keema':              { cal: 210, unit: 'per bowl' },
  'soya keema masala':       { cal: 230, unit: 'per bowl' },
  'soya kheema':             { cal: 210, unit: 'per bowl' },
  'soya masala':             { cal: 220, unit: 'per bowl' },
  'soya do pyaza':           { cal: 240, unit: 'per bowl' },
  'soya bhurji':             { cal: 200, unit: 'per bowl' },
  'soya pulao':              { cal: 290, unit: 'per plate' },
  'soya biryani':            { cal: 380, unit: 'per plate' },
  'tofu':                    { cal: 76,  unit: 'per 100g' },
  'tofu curry':              { cal: 160, unit: 'per bowl' },
  'tofu bhurji':             { cal: 180, unit: 'per bowl' },
  'tofu stir fry':           { cal: 200, unit: 'per bowl' },
  'tofu tikka':              { cal: 220, unit: 'per plate' },

  // ═══ MORE CURRIES & GRAVIES ═══
  'arbi curry':              { cal: 180, unit: 'per bowl' },
  'arbi masala':             { cal: 190, unit: 'per bowl' },
  'kathal curry':            { cal: 200, unit: 'per bowl' },
  'kathal masala':           { cal: 210, unit: 'per bowl' },
  'jackfruit curry':         { cal: 200, unit: 'per bowl' },
  'raw banana curry':        { cal: 170, unit: 'per bowl' },
  'raw banana masala':       { cal: 175, unit: 'per bowl' },
  'kela curry':              { cal: 170, unit: 'per bowl' },
  'yam curry':               { cal: 160, unit: 'per bowl' },
  'suran curry':             { cal: 160, unit: 'per bowl' },
  'jimikand curry':          { cal: 165, unit: 'per bowl' },
  'lotus stem curry':        { cal: 150, unit: 'per bowl' },
  'kamal kakdi curry':       { cal: 150, unit: 'per bowl' },
  'singhare ki sabzi':       { cal: 140, unit: 'per bowl' },
  'lauki curry':             { cal: 110, unit: 'per bowl' },
  'lauki sabzi':             { cal: 100, unit: 'per bowl' },
  'ghiya curry':             { cal: 110, unit: 'per bowl' },
  'bottle gourd curry':      { cal: 110, unit: 'per bowl' },
  'tinda curry':             { cal: 120, unit: 'per bowl' },
  'tinda masala':            { cal: 125, unit: 'per bowl' },
  'karela curry':            { cal: 130, unit: 'per bowl' },
  'bitter gourd curry':      { cal: 130, unit: 'per bowl' },
  'karela masala':           { cal: 140, unit: 'per bowl' },
  'parwal curry':            { cal: 130, unit: 'per bowl' },
  'pointed gourd curry':     { cal: 130, unit: 'per bowl' },
  'turai curry':             { cal: 100, unit: 'per bowl' },
  'ridge gourd curry':       { cal: 100, unit: 'per bowl' },
  'pumpkin curry':           { cal: 130, unit: 'per bowl' },
  'kaddu curry':             { cal: 130, unit: 'per bowl' },
  'kaddu sabzi':             { cal: 125, unit: 'per bowl' },
  'tomato curry':            { cal: 120, unit: 'per bowl' },
  'tamatar sabzi':           { cal: 120, unit: 'per bowl' },
  'spinach curry':           { cal: 110, unit: 'per bowl' },
  'palak sabzi':             { cal: 110, unit: 'per bowl' },
  'saag':                    { cal: 150, unit: 'per bowl' },
  'sarson ka saag':          { cal: 170, unit: 'per bowl' },
  'methi sabzi':             { cal: 120, unit: 'per bowl' },
  'fenugreek curry':         { cal: 120, unit: 'per bowl' },
  'sem curry':               { cal: 140, unit: 'per bowl' },
  'sem ki phali':            { cal: 130, unit: 'per bowl' },
  'french beans curry':      { cal: 120, unit: 'per bowl' },
  'beans sabzi':             { cal: 120, unit: 'per bowl' },
  'gawar curry':             { cal: 110, unit: 'per bowl' },
  'cluster beans curry':     { cal: 110, unit: 'per bowl' },
  'kali dal':                { cal: 180, unit: 'per bowl' },
  'urad dal curry':          { cal: 160, unit: 'per bowl' },
  'chana curry':             { cal: 190, unit: 'per bowl' },
  'kala chana curry':        { cal: 200, unit: 'per bowl' },
  'kala chana masala':       { cal: 210, unit: 'per bowl' },
  'kabuli chana':            { cal: 190, unit: 'per bowl' },
  'moong curry':             { cal: 150, unit: 'per bowl' },
  'moong masala':            { cal: 160, unit: 'per bowl' },
  'green moong curry':       { cal: 160, unit: 'per bowl' },
  'sabut moong':             { cal: 155, unit: 'per bowl' },
  'lobia curry':             { cal: 170, unit: 'per bowl' },
  'black eyed peas curry':   { cal: 170, unit: 'per bowl' },
  'moth curry':              { cal: 175, unit: 'per bowl' },
  'masoor curry':            { cal: 160, unit: 'per bowl' },
  'red lentil curry':        { cal: 160, unit: 'per bowl' },
  'matki curry':             { cal: 170, unit: 'per bowl' },
  'vatana curry':            { cal: 180, unit: 'per bowl' },
  'sukhi sabzi':             { cal: 120, unit: 'per bowl' },
  'aloo tamatar':            { cal: 160, unit: 'per bowl' },
  'aloo methi':              { cal: 170, unit: 'per bowl' },
  'aloo jeera':              { cal: 160, unit: 'per bowl' },
  'aloo pyaz':               { cal: 165, unit: 'per bowl' },
  'aloo shimla mirch':       { cal: 155, unit: 'per bowl' },
  'capsicum sabzi':          { cal: 110, unit: 'per bowl' },
  'broccoli curry':          { cal: 120, unit: 'per bowl' },
  'baby corn curry':         { cal: 150, unit: 'per bowl' },
  'sweet corn curry':        { cal: 160, unit: 'per bowl' },
  'corn masala':             { cal: 165, unit: 'per bowl' },

  // ═══ CHICKEN DISHES ═══
  'chicken do pyaza':        { cal: 290, unit: 'per bowl' },
  'chicken korma':           { cal: 380, unit: 'per bowl' },
  'chicken handi':           { cal: 340, unit: 'per bowl' },
  'chicken kadai':           { cal: 350, unit: 'per bowl' },
  'kadai chicken':           { cal: 350, unit: 'per bowl' },
  'chicken saag':            { cal: 280, unit: 'per bowl' },
  'palak chicken':           { cal: 280, unit: 'per bowl' },
  'chicken rezala':          { cal: 300, unit: 'per bowl' },
  'chicken changezi':        { cal: 370, unit: 'per bowl' },
  'chicken makhani':         { cal: 380, unit: 'per bowl' },
  'chicken keema':           { cal: 280, unit: 'per bowl' },
  'keema matar':             { cal: 300, unit: 'per bowl' },
  'chicken kofta':           { cal: 310, unit: 'per bowl' },
  'chicken 65':              { cal: 300, unit: 'per plate' },
  'chicken malai tikka':     { cal: 230, unit: 'per plate' },
  'chicken boti':            { cal: 210, unit: 'per plate' },
  'chicken seekh kebab':     { cal: 220, unit: 'per plate' },
  'chicken reshmi kebab':    { cal: 230, unit: 'per plate' },
  'chicken galouti':         { cal: 250, unit: 'per plate' },
  'chicken shawarma':        { cal: 360, unit: 'per roll' },
  'chicken roll':            { cal: 350, unit: 'per roll' },
  'chicken wrap':            { cal: 340, unit: 'per wrap' },
  'chicken biryani plate':   { cal: 490, unit: 'per plate' },
  'half chicken':            { cal: 360, unit: 'per half' },
  'full chicken':            { cal: 720, unit: 'per full' },
  'roast chicken':           { cal: 180, unit: 'per 100g' },
  'fried chicken':           { cal: 250, unit: 'per piece' },

  // ═══ MUTTON / LAMB ═══
  'mutton curry':            { cal: 360, unit: 'per bowl' },
  'mutton korma':            { cal: 400, unit: 'per bowl' },
  'mutton rogan josh':       { cal: 380, unit: 'per bowl' },
  'rogan josh':              { cal: 380, unit: 'per bowl' },
  'mutton do pyaza':         { cal: 350, unit: 'per bowl' },
  'mutton handi':            { cal: 370, unit: 'per bowl' },
  'mutton keema':            { cal: 310, unit: 'per bowl' },
  'keema':                   { cal: 290, unit: 'per bowl' },
  'mutton seekh kebab':      { cal: 240, unit: 'per plate' },
  'mutton galouti':          { cal: 260, unit: 'per plate' },
  'mutton shami kebab':      { cal: 250, unit: 'per plate' },
  'mutton kofta':            { cal: 320, unit: 'per bowl' },
  'mutton nihari':           { cal: 400, unit: 'per bowl' },
  'nihari':                  { cal: 400, unit: 'per bowl' },
  'paya':                    { cal: 250, unit: 'per bowl' },
  'lamb curry':              { cal: 360, unit: 'per bowl' },

  // ═══ FISH & SEAFOOD ═══
  'fish curry':              { cal: 220, unit: 'per bowl' },
  'fish masala':             { cal: 240, unit: 'per bowl' },
  'fish fry':                { cal: 230, unit: 'per piece' },
  'fish tikka':              { cal: 200, unit: 'per plate' },
  'rohu curry':              { cal: 200, unit: 'per bowl' },
  'katla curry':             { cal: 210, unit: 'per bowl' },
  'pomfret fry':             { cal: 220, unit: 'per piece' },
  'pomfret curry':           { cal: 230, unit: 'per bowl' },
  'surmai fry':              { cal: 200, unit: 'per piece' },
  'prawn curry':             { cal: 240, unit: 'per bowl' },
  'prawn masala':            { cal: 250, unit: 'per bowl' },
  'prawns':                  { cal: 100, unit: 'per 100g' },
  'prawn biryani':           { cal: 460, unit: 'per plate' },
  'crab curry':              { cal: 180, unit: 'per bowl' },
  'tuna':                    { cal: 130, unit: 'per 100g' },
  'salmon':                  { cal: 200, unit: 'per 100g' },

  // ═══ MORE STREET FOOD / DELHI SPECIFIC ═══
  'chole kulche':            { cal: 420, unit: 'per plate' },
  'kulcha':                  { cal: 220, unit: 'per piece' },
  'aloo kulcha':             { cal: 280, unit: 'per piece' },
  'paneer kulcha':           { cal: 300, unit: 'per piece' },
  'bedmi puri':              { cal: 180, unit: 'per piece' },
  'bedmi':                   { cal: 170, unit: 'per piece' },
  'dahi bhalla':             { cal: 180, unit: 'per piece' },
  'golgappa puri':           { cal: 35,  unit: 'per piece' },
  'pani puri plate':         { cal: 200, unit: 'per plate (6 pcs)' },
  'papdi chaat':             { cal: 220, unit: 'per plate' },
  'aloo chaat plate':        { cal: 220, unit: 'per plate' },
  'fruit chaat':             { cal: 150, unit: 'per plate' },
  'corn chaat':              { cal: 180, unit: 'per plate' },
  'dahi papdi chaat':        { cal: 250, unit: 'per plate' },
  'raj kachori':             { cal: 350, unit: 'per piece' },
  'dahi kachori':            { cal: 280, unit: 'per piece' },
  'matar kulcha':            { cal: 380, unit: 'per plate' },
  'chur chur naan':          { cal: 400, unit: 'per piece' },
  'aloo chur chur naan':     { cal: 430, unit: 'per piece' },
  'paneer chur chur naan':   { cal: 460, unit: 'per piece' },
  'paranthe wali gali':      { cal: 280, unit: 'per paratha' },
  'stuffed paratha':         { cal: 280, unit: 'per piece' },
  'mix paratha':             { cal: 260, unit: 'per piece' },
  'laccha paratha':          { cal: 300, unit: 'per piece' },
  'rumali roti':             { cal: 120, unit: 'per piece' },
  'sheermal':                { cal: 250, unit: 'per piece' },
  'bakarkhani':              { cal: 300, unit: 'per piece' },
  'tandoori paratha':        { cal: 210, unit: 'per piece' },
  'bun maska':               { cal: 280, unit: 'per piece' },
  'kachori sabzi':           { cal: 380, unit: 'per plate' },
  'jalebi fafda':            { cal: 300, unit: 'per plate' },
  'pyaz kachori':            { cal: 220, unit: 'per piece' },
  'dal kachori':             { cal: 230, unit: 'per piece' },

  // ═══ ROLLS & WRAPS ═══
  'egg roll':                { cal: 280, unit: 'per roll' },
  'paneer roll':             { cal: 320, unit: 'per roll' },
  'veg roll':                { cal: 290, unit: 'per roll' },
  'frankie':                 { cal: 310, unit: 'per roll' },
  'kathi roll':              { cal: 330, unit: 'per roll' },
  'shawarma':                { cal: 370, unit: 'per roll' },
  'falafel wrap':            { cal: 350, unit: 'per wrap' },
  'chapati roll':            { cal: 280, unit: 'per roll' },

  // ═══ RAJASTHANI / NORTH INDIAN REGIONAL ═══
  'dal baati churma':        { cal: 650, unit: 'per plate' },
  'baati':                   { cal: 200, unit: 'per piece' },
  'churma':                  { cal: 300, unit: 'per bowl' },
  'gatte ki sabzi':          { cal: 230, unit: 'per bowl' },
  'gatte ki curry':          { cal: 230, unit: 'per bowl' },
  'ker sangri':              { cal: 180, unit: 'per bowl' },
  'bajre ki khichdi':        { cal: 220, unit: 'per bowl' },
  'laal maas':               { cal: 380, unit: 'per bowl' },
  'safed maas':              { cal: 360, unit: 'per bowl' },
  'kadhi pakoda':            { cal: 200, unit: 'per bowl' },
  'mohan maas':              { cal: 390, unit: 'per bowl' },

  // ═══ PUNJABI SPECIALS ═══
  'butter chicken plate':    { cal: 420, unit: 'per plate' },
  'dal makhani plate':       { cal: 280, unit: 'per bowl' },
  'amritsari kulcha':        { cal: 350, unit: 'per piece' },
  'amritsari fish':          { cal: 260, unit: 'per plate' },
  'amritsari chicken':       { cal: 280, unit: 'per plate' },
  'pindi chole':             { cal: 230, unit: 'per bowl' },
  'sarson saag':             { cal: 170, unit: 'per bowl' },
  'makke di roti':           { cal: 120, unit: 'per piece' },
  'punjabi kadhi':           { cal: 190, unit: 'per bowl' },
  'pinni':                   { cal: 200, unit: 'per piece' },

  // ═══ BENGALI SPECIALS ═══
  'aloo posto':              { cal: 200, unit: 'per bowl' },
  'shorshe ilish':           { cal: 300, unit: 'per bowl' },
  'hilsa curry':             { cal: 300, unit: 'per bowl' },
  'doi maach':               { cal: 260, unit: 'per bowl' },
  'chingri malai curry':     { cal: 310, unit: 'per bowl' },
  'kosha mangsho':           { cal: 380, unit: 'per bowl' },
  'macher jhol':             { cal: 220, unit: 'per bowl' },
  'begun bhaja':             { cal: 150, unit: 'per piece' },
  'luchi':                   { cal: 90,  unit: 'per piece' },
  'tarka dal bengali':       { cal: 150, unit: 'per bowl' },

  // ═══ GUJARATI SPECIALS ═══
  'dhokla':                  { cal: 160, unit: 'per plate' },
  'khaman dhokla':           { cal: 160, unit: 'per plate' },
  'handvo':                  { cal: 200, unit: 'per piece' },
  'thepla':                  { cal: 130, unit: 'per piece' },
  'methi thepla':            { cal: 140, unit: 'per piece' },
  'undhiyu':                 { cal: 250, unit: 'per bowl' },
  'shrikhand':               { cal: 180, unit: 'per bowl' },
  'basundi':                 { cal: 200, unit: 'per bowl' },
  'khandvi':                 { cal: 120, unit: 'per plate' },
  'fafda':                   { cal: 180, unit: 'per plate' },
  'sev tameta':              { cal: 150, unit: 'per bowl' },
  'surti locho':             { cal: 200, unit: 'per plate' },
  'dal dhokli':              { cal: 260, unit: 'per bowl' },

  // ═══ HYDERABADI / ANDHRA ═══
  'pesarattu':               { cal: 150, unit: 'per piece' },
  'gongura chicken':         { cal: 310, unit: 'per bowl' },
  'gongura mutton':          { cal: 370, unit: 'per bowl' },
  'kodi kura':               { cal: 300, unit: 'per bowl' },
  'bagara baingan':          { cal: 220, unit: 'per bowl' },
  'mirchi ka salan':         { cal: 200, unit: 'per bowl' },
  'double ka meetha':        { cal: 280, unit: 'per serving' },
  'haleem':                  { cal: 350, unit: 'per bowl' },
  'paya soup':               { cal: 200, unit: 'per bowl' },
  'sheer korma':             { cal: 250, unit: 'per bowl' },

  // ═══ MAHARASHTRIAN ═══
  'misal pav':               { cal: 350, unit: 'per plate' },
  'pav bhaji plate':         { cal: 400, unit: 'per plate' },
  'sabudana khichdi':        { cal: 280, unit: 'per bowl' },
  'sabudana vada':           { cal: 180, unit: 'per piece' },
  'puran poli':              { cal: 230, unit: 'per piece' },
  'modak':                   { cal: 120, unit: 'per piece' },
  'ukadiche modak':          { cal: 100, unit: 'per piece' },
  'thalipeeth':              { cal: 200, unit: 'per piece' },
  'vangi bhaat':             { cal: 290, unit: 'per plate' },
  'kothimbir vadi':          { cal: 180, unit: 'per plate' },
  'kolhapuri chicken':       { cal: 340, unit: 'per bowl' },
  'kolhapuri mutton':        { cal: 390, unit: 'per bowl' },

  // ═══ CHINESE / INDO-CHINESE ═══
  'veg hakka noodles':       { cal: 290, unit: 'per bowl' },
  'chicken hakka noodles':   { cal: 340, unit: 'per bowl' },
  'schezwan noodles':        { cal: 350, unit: 'per bowl' },
  'fried rice chinese':      { cal: 340, unit: 'per bowl' },
  'veg manchow soup':        { cal: 90,  unit: 'per bowl' },
  'hot and sour soup':       { cal: 100, unit: 'per bowl' },
  'veg spring roll':         { cal: 100, unit: 'per piece' },
  'chicken spring roll':     { cal: 130, unit: 'per piece' },
  'crispy veg':              { cal: 250, unit: 'per bowl' },
  'crispy chicken':          { cal: 300, unit: 'per bowl' },
  'schezwan chicken':        { cal: 290, unit: 'per bowl' },
  'honey chili potato':      { cal: 280, unit: 'per bowl' },
  'chili garlic noodles':    { cal: 320, unit: 'per bowl' },
  'kung pao chicken':        { cal: 290, unit: 'per bowl' },

  // ═══ RICE DISHES EXPANDED ═══
  'prawn biryani':           { cal: 460, unit: 'per plate' },
  'fish biryani':            { cal: 440, unit: 'per plate' },
  'soya biryani':            { cal: 380, unit: 'per plate' },
  'paneer biryani':          { cal: 430, unit: 'per plate' },
  'mushroom biryani':        { cal: 380, unit: 'per plate' },
  'egg biryani full':        { cal: 450, unit: 'per plate' },
  'sindhi biryani':          { cal: 480, unit: 'per plate' },
  'ambur biryani':           { cal: 460, unit: 'per plate' },
  'thalassery biryani':      { cal: 450, unit: 'per plate' },
  'mandi':                   { cal: 550, unit: 'per plate' },
  'kabsa':                   { cal: 520, unit: 'per plate' },
  'tahri':                   { cal: 300, unit: 'per plate' },
  'tehri':                   { cal: 300, unit: 'per plate' },
  'lemon rice':              { cal: 200, unit: 'per cup' },
  'tamarind rice':           { cal: 210, unit: 'per cup' },
  'coconut rice':            { cal: 240, unit: 'per cup' },
  'tomato rice':             { cal: 210, unit: 'per cup' },
  'peas rice':               { cal: 220, unit: 'per cup' },
  'vegetable rice':          { cal: 230, unit: 'per cup' },

  // ═══ MORE KEBABS & TIKKA ═══
  'paneer tikka':            { cal: 290, unit: 'per plate' },
  'fish tikka':              { cal: 220, unit: 'per plate' },
  'prawn tikka':             { cal: 230, unit: 'per plate' },
  'veg seekh kebab':         { cal: 160, unit: 'per piece' },
  'veg tikka':               { cal: 150, unit: 'per plate' },
  'boti kebab':              { cal: 190, unit: 'per piece' },
  'shammi kebab':            { cal: 180, unit: 'per piece' },
  'kakori kebab':            { cal: 200, unit: 'per piece' },
  'dahi kebab':              { cal: 170, unit: 'per piece' },

  // ═══ MORE SNACKS ═══
  'matar kulcha snack':      { cal: 300, unit: 'per plate' },
  'raj kachori plate':       { cal: 350, unit: 'per plate' },
  'aloo bonda':              { cal: 130, unit: 'per piece' },
  'bonda':                   { cal: 120, unit: 'per piece' },
  'bajji':                   { cal: 80,  unit: 'per piece' },
  'mirchi bajji':            { cal: 90,  unit: 'per piece' },
  'punugulu':                { cal: 70,  unit: 'per piece' },
  'bread roll':              { cal: 130, unit: 'per piece' },
  'pinwheel':                { cal: 80,  unit: 'per piece' },
  'puff pastry':             { cal: 220, unit: 'per piece' },
  'veg puff':                { cal: 200, unit: 'per piece' },
  'chicken puff':            { cal: 240, unit: 'per piece' },
  'patties':                 { cal: 180, unit: 'per piece' },
  'veg patties':             { cal: 160, unit: 'per piece' },
  'corn patties':            { cal: 150, unit: 'per piece' },
  'nachos with cheese':      { cal: 400, unit: 'per plate' },
  'tortilla chips':          { cal: 140, unit: 'per small pack' },
  'popcorn':                 { cal: 100, unit: 'per small bowl' },
  'caramel popcorn':         { cal: 160, unit: 'per small bowl' },
  'peanut butter':           { cal: 190, unit: 'per 2 tbsp' },
  'hummus':                  { cal: 170, unit: 'per bowl' },

  // ═══ BEVERAGES EXPANDED ═══
  'filter coffee':           { cal: 65,  unit: 'per cup' },
  'south indian coffee':     { cal: 70,  unit: 'per cup' },
  'cold brew':               { cal: 5,   unit: 'per glass' },
  'doodh':                   { cal: 120, unit: 'per glass' },
  'haldi doodh':             { cal: 130, unit: 'per glass' },
  'golden milk':             { cal: 130, unit: 'per glass' },
  'badam milk':              { cal: 160, unit: 'per glass' },
  'kesar milk':              { cal: 150, unit: 'per glass' },
  'rose milk':               { cal: 140, unit: 'per glass' },
  'thandai':                 { cal: 200, unit: 'per glass' },
  'aam panna':               { cal: 80,  unit: 'per glass' },
  'kanji':                   { cal: 40,  unit: 'per glass' },
  'sattu drink':             { cal: 120, unit: 'per glass' },
  'sugarcane juice':         { cal: 180, unit: 'per glass' },
  'bael sharbat':            { cal: 90,  unit: 'per glass' },
  'kokum sharbat':           { cal: 80,  unit: 'per glass' },
  'glucose drink':           { cal: 100, unit: 'per glass' },
  'energy drink':            { cal: 110, unit: 'per can' },
  'cola':                    { cal: 140, unit: 'per can' },
  'coke':                    { cal: 140, unit: 'per can' },
  'pepsi':                   { cal: 140, unit: 'per can' },
  'sprite':                  { cal: 120, unit: 'per can' },
  'soft drink':              { cal: 130, unit: 'per can' },
  'diet coke':               { cal: 5,   unit: 'per can' },

  // ═══ SWEETS EXPANDED ═══
  'moong dal halwa':         { cal: 290, unit: 'per bowl' },
  'suji halwa':              { cal: 230, unit: 'per bowl' },
  'atta halwa':              { cal: 250, unit: 'per bowl' },
  'sooji halwa':             { cal: 230, unit: 'per bowl' },
  'gajar ka halwa':          { cal: 260, unit: 'per bowl' },
  'badam ka halwa':          { cal: 320, unit: 'per bowl' },
  'besan halwa':             { cal: 300, unit: 'per bowl' },
  'lauki halwa':             { cal: 200, unit: 'per bowl' },
  'kaju halwa':              { cal: 330, unit: 'per bowl' },
  'imarti':                  { cal: 140, unit: 'per piece' },
  'malpua':                  { cal: 190, unit: 'per piece' },
  'balushahi':               { cal: 160, unit: 'per piece' },
  'gujiya':                  { cal: 200, unit: 'per piece' },
  'karanji':                 { cal: 200, unit: 'per piece' },
  'til ladoo':               { cal: 130, unit: 'per piece' },
  'coconut ladoo':           { cal: 110, unit: 'per piece' },
  'rava ladoo':              { cal: 140, unit: 'per piece' },
  'motichoor ladoo':         { cal: 130, unit: 'per piece' },
  'malai peda':              { cal: 130, unit: 'per piece' },
  'kesar peda':              { cal: 135, unit: 'per piece' },
  'soan papdi':              { cal: 70,  unit: 'per piece' },
  'milk cake':               { cal: 150, unit: 'per piece' },
  'petha':                   { cal: 110, unit: 'per piece' },
  'gajak':                   { cal: 140, unit: 'per piece' },
  'revdi':                   { cal: 80,  unit: 'per piece' },
  'chikki':                  { cal: 130, unit: 'per piece' },
  'peanut chikki':           { cal: 135, unit: 'per piece' },
  'til chikki':              { cal: 140, unit: 'per piece' },
  'cham cham':               { cal: 140, unit: 'per piece' },
  'pantua':                  { cal: 150, unit: 'per piece' },
  'sandesh':                 { cal: 100, unit: 'per piece' },
  'mihidana':                { cal: 90,  unit: 'per piece' },
  'kheer mohan':             { cal: 110, unit: 'per piece' },
  'mysore pak':              { cal: 180, unit: 'per piece' },
  'dharwad peda':            { cal: 140, unit: 'per piece' },
  'karigadabu':              { cal: 160, unit: 'per piece' },
  'payasam':                 { cal: 190, unit: 'per bowl' },
  'ada pradhaman':           { cal: 200, unit: 'per bowl' },
  'paal payasam':            { cal: 180, unit: 'per bowl' },
  'semiya payasam':          { cal: 190, unit: 'per bowl' },
  'vermicelli kheer':        { cal: 200, unit: 'per bowl' },
  'sabudana kheer':          { cal: 210, unit: 'per bowl' },
  'pista ice cream':         { cal: 210, unit: 'per scoop' },
  'mango ice cream':         { cal: 220, unit: 'per scoop' },
  'chocolate ice cream':     { cal: 230, unit: 'per scoop' },
  'softy':                   { cal: 160, unit: 'per cone' },
  'ice cream cone':          { cal: 180, unit: 'per cone' },

  // ═══ PROTEIN / GYM FOOD ═══
  'whey protein':            { cal: 120, unit: 'per scoop' },
  'protein powder':          { cal: 120, unit: 'per scoop' },
  'mass gainer':             { cal: 400, unit: 'per serving' },
  'creatine':                { cal: 0,   unit: 'per serving' },
  'bcaa':                    { cal: 10,  unit: 'per serving' },
  'peanut butter sandwich':  { cal: 350, unit: 'per sandwich' },
  'boiled chicken breast':   { cal: 165, unit: 'per 100g' },
  'egg white':               { cal: 17,  unit: 'per egg white' },
  'tuna sandwich':           { cal: 280, unit: 'per sandwich' },
  'protein bar':             { cal: 200, unit: 'per bar' },
  'granola bar':             { cal: 190, unit: 'per bar' },
  'greek yogurt bowl':       { cal: 130, unit: 'per bowl' },
  'cottage cheese':          { cal: 110, unit: 'per 100g' },
  'sprouts':                 { cal: 80,  unit: 'per bowl' },
  'mixed sprouts':           { cal: 80,  unit: 'per bowl' },
  'moong sprouts':           { cal: 75,  unit: 'per bowl' },
  'chana sprouts':           { cal: 90,  unit: 'per bowl' },

  // ═══ ROTI VARIATIONS ═══
  'missi roti':              { cal: 100, unit: 'per piece' },
  'bajra roti':              { cal: 100, unit: 'per piece' },
  'jowar roti':              { cal: 85,  unit: 'per piece' },
  'ragi roti':               { cal: 90,  unit: 'per piece' },
  'nachni roti':             { cal: 90,  unit: 'per piece' },
  'kuttu roti':              { cal: 100, unit: 'per piece' },
  'singhara roti':           { cal: 95,  unit: 'per piece' },
  'wheat roti':              { cal: 70,  unit: 'per piece' },
  'multigrain roti':         { cal: 80,  unit: 'per piece' },
  'besan roti':              { cal: 90,  unit: 'per piece' },
  'palak roti':              { cal: 75,  unit: 'per piece' },
  'methi roti':              { cal: 78,  unit: 'per piece' },
  'ajwain roti':             { cal: 72,  unit: 'per piece' },
  'pyaz roti':               { cal: 80,  unit: 'per piece' },

  // ═══ COMBO PLATES / THALI ═══
  'veg thali':               { cal: 700, unit: 'per thali' },
  'non veg thali':           { cal: 850, unit: 'per thali' },
  'rajasthani thali':        { cal: 800, unit: 'per thali' },
  'gujarati thali':          { cal: 750, unit: 'per thali' },
  'south indian thali':      { cal: 680, unit: 'per thali' },
  'punjabi thali':           { cal: 820, unit: 'per thali' },
  'mini thali':              { cal: 450, unit: 'per thali' },
  'meal plate':              { cal: 550, unit: 'per plate' },

  // ═══ EGGS EXPANDED ═══
  'poached egg':             { cal: 70,  unit: 'per egg' },
  'hard boiled egg':         { cal: 70,  unit: 'per egg' },
  'soft boiled egg':         { cal: 65,  unit: 'per egg' },
  'egg bhurji':              { cal: 200, unit: 'per serving (2 eggs)' },
  'masala omelette':         { cal: 180, unit: 'per omelette (2 eggs)' },
  'plain omelette':          { cal: 150, unit: 'per omelette (2 eggs)' },
  'egg sandwich':            { cal: 280, unit: 'per sandwich' },
  'egg paratha':             { cal: 250, unit: 'per piece' },
  'egg dosa':                { cal: 200, unit: 'per piece' },
  'egg fried rice':          { cal: 360, unit: 'per bowl' },
  'half fry':                { cal: 90,  unit: 'per egg' },
  'double omelette':         { cal: 300, unit: 'per omelette' },
};

// ── Update CATEGORY_FALLBACKS to also include soya ────────────────────────────

// ── Category calorie averages for smart fallback ─────────────────────────────
const CATEGORY_FALLBACKS: Array<{ keywords: string[]; cal: number; unit: string }> = [
  { keywords: ['biryani','rice','pulao','tahri','tehri','mandi'],    cal: 430, unit: 'per plate' },
  { keywords: ['soya chaap','chaap'],                                cal: 300, unit: 'per plate' },
  { keywords: ['soya','soyabean','tofu'],                            cal: 210, unit: 'per bowl'  },
  { keywords: ['curry','masala','sabzi','gravy','handi','korma'],    cal: 220, unit: 'per bowl'  },
  { keywords: ['dal','lentil','rajma','chole','chana'],              cal: 180, unit: 'per bowl'  },
  { keywords: ['roti','naan','paratha','bread','kulcha','chapati'],  cal: 150, unit: 'per piece' },
  { keywords: ['samosa','pakora','tikki','vada','bonda','bajji'],    cal: 130, unit: 'per piece' },
  { keywords: ['momos','momo','dumpling'],                           cal: 35,  unit: 'per piece' },
  { keywords: ['dosa','uttapam','idli','appam'],                     cal: 120, unit: 'per piece' },
  { keywords: ['soup','rasam','shorba'],                             cal: 80,  unit: 'per bowl'  },
  { keywords: ['halwa','kheer','payasam','pudding'],                 cal: 220, unit: 'per bowl'  },
  { keywords: ['ladoo','barfi','peda','sweet','mithai'],             cal: 130, unit: 'per piece' },
  { keywords: ['ice cream','kulfi','softy'],                         cal: 200, unit: 'per scoop' },
  { keywords: ['shake','smoothie','lassi'],                          cal: 200, unit: 'per glass' },
  { keywords: ['juice'],                                             cal: 120, unit: 'per glass' },
  { keywords: ['tea','chai'],                                        cal: 45,  unit: 'per cup'   },
  { keywords: ['coffee'],                                            cal: 50,  unit: 'per cup'   },
  { keywords: ['salad','kachumber'],                                 cal: 60,  unit: 'per plate' },
  { keywords: ['kebab','tikka','tandoori','boti'],                   cal: 160, unit: 'per piece' },
  { keywords: ['burger','sandwich','wrap','roll','frankie'],         cal: 310, unit: 'per piece' },
  { keywords: ['pizza'],                                             cal: 285, unit: 'per slice' },
  { keywords: ['pasta','noodles','chowmein','hakka'],                cal: 310, unit: 'per bowl'  },
  { keywords: ['egg','omelette','bhurji'],                           cal: 80,  unit: 'per egg'   },
  { keywords: ['chicken'],                                           cal: 260, unit: 'per serving'},
  { keywords: ['mutton','lamb','gosht'],                             cal: 360, unit: 'per serving'},
  { keywords: ['fish','prawn','seafood'],                            cal: 220, unit: 'per serving'},
  { keywords: ['paneer'],                                            cal: 270, unit: 'per serving'},
  { keywords: ['fruit'],                                             cal: 80,  unit: 'per piece' },
  { keywords: ['thali'],                                             cal: 700, unit: 'per thali' },
  { keywords: ['protein','whey'],                                    cal: 120, unit: 'per scoop' },
];

export function getFoodSuggestions(query: string): string[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return Object.keys(FOOD_DATABASE)
    .filter(key => key.includes(q) || q.includes(key))
    .slice(0, 8);
}

// Richer version for components that want calories + unit in suggestions
export function getFoodSuggestionsRich(query: string): Array<{ name: string; calories: number; unit: string }> {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return Object.entries(FOOD_DATABASE)
    .filter(([key]) => key.includes(q) || q.includes(key))
    .slice(0, 8)
    .map(([name, { cal, unit }]) => ({ name, calories: cal, unit }));
}

export function estimateCalories(food: string, quantity = 1): FoodItem {
  const normalized = food.toLowerCase().trim();

  // 1. Exact match
  const exact = FOOD_DATABASE[normalized];
  if (exact) {
    return {
      food: `${quantity > 1 ? quantity + '× ' : ''}${food}`,
      calories: exact.cal * quantity,
      confidence: 'high',
      unit: exact.unit,
    };
  }

  // 2. Best partial match (longest key that matches)
  let bestKey = '';
  for (const key of Object.keys(FOOD_DATABASE)) {
    if ((normalized.includes(key) || key.includes(normalized)) && key.length > bestKey.length) {
      bestKey = key;
    }
  }
  if (bestKey) {
    const match = FOOD_DATABASE[bestKey];
    return {
      food: `${quantity > 1 ? quantity + '× ' : ''}${food}`,
      calories: match.cal * quantity,
      confidence: 'medium',
      unit: match.unit,
    };
  }

  // 3. Category fallback — smarter than a flat 150
  for (const cat of CATEGORY_FALLBACKS) {
    if (cat.keywords.some(kw => normalized.includes(kw))) {
      return {
        food: `${quantity > 1 ? quantity + '× ' : ''}${food}`,
        calories: cat.cal * quantity,
        confidence: 'low',
        unit: cat.unit,
      };
    }
  }

  // 4. Last resort — generic 200 cal with low confidence
  return {
    food: `${quantity > 1 ? quantity + '× ' : ''}${food}`,
    calories: 200 * quantity,
    confidence: 'low',
    unit: 'per serving',
  };
}
